### ISSUE TITLE
Fix usage of useWallet hook in default app component

### ISSUE THREAD

**Issue by iskysun96** [algorandfoundation/algokit-react-frontend-template#19]
useWallet hook cannot be used in the root App component. It can only be used in a component that's a child of WalletProvider
The template is still using v2.1.1, but the latest version shows a more descriptive error explaining this.

Since this is a common mistake a lot of devs make, we should upgrade to the latest version of use-wallet.

**Comment by aorumbayev** [comment]
Please note, this is non issue, the package json in the jinja template isn't locked to v2.1.1, upon install it grabs the latest version for v2.x.x - unless use-wallet does v3 we can safely assume new template instances always grab the latest version. You can check that by going to package lock of a fresh react template to note that its using the 2.4.0. 

However the app component using useWallet hook needs to be patched - see fix in the following PR https://github.com/algorandfoundation/algokit-react-frontend-template/pull/22

**Comment by aorumbayev** [comment]
Patching the useWallet hook usage in https://github.com/algorandfoundation/algokit-react-frontend-template/pull/22. 

@iskysun96 please note fullstack template will be updated later on to update the injector part to match the new App.tsx content, the standalone react template however now has the fix for the hook usage
